# Generated by Django 3.1.5 on 2021-01-28 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('regdate', models.DateTimeField(default=datetime.datetime(2021, 1, 28, 2, 2, 46, 344476, tzinfo=utc))),
                ('viewcnt', models.IntegerField(default=0)),
            ],
        ),
    ]
