# Generated by Django 3.1.5 on 2021-02-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0003_auto_20210215_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('prep', '준비중'), ('ord', '주문'), ('done', '완료')], max_length=20, verbose_name='완료여부'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobtitle',
            field=models.CharField(choices=[('J20', '메니저'), ('J10', 'CEO'), ('J50', '아르바이트'), ('J30', '사원'), ('J40', '인턴')], max_length=20, verbose_name='직급'),
        ),
    ]
