# Generated by Django 3.1.6 on 2021-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0003_auto_20210215_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ord', '주문'), ('prep', '준비중'), ('done', '완료')], max_length=20, verbose_name='완료여부'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobtitle',
            field=models.CharField(choices=[('J20', '메니저'), ('J30', '사원'), ('J40', '인턴'), ('J50', '아르바이트'), ('J10', 'CEO')], max_length=20, verbose_name='직급'),
        ),
    ]
