# Generated by Django 3.1.6 on 2021-02-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0004_auto_20210215_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('done', '완료'), ('prep', '준비중'), ('ord', '주문')], max_length=20, verbose_name='완료여부'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobtitle',
            field=models.CharField(choices=[('J50', '아르바이트'), ('J10', 'CEO'), ('J30', '사원'), ('J20', '메니저'), ('J40', '인턴')], max_length=20, verbose_name='직급'),
        ),
    ]
