-- 부서가 없음에도 불구하고 보너스를 지급받는 직원의 이름, 부서, 보너스를 조회한다면?
-- IS NULL, IS NOT NULL
SELECT EMP_NAME, DEPT_ID, BONUS_PCT
FROM EMPLOYEE
WHERE DEPT_ID IS NULL AND BONUS_PCT IS NOT NULL ;

--IN = OR 와 동일하다.

SELECT EMP_NAME, DEPT_ID, SALARY
FROM EMPLOYEE
WHERE DEPT_ID IN ('20', '90');

--부서번호가 20번 또는 90번인 사원 중 급여가 3000000 보다 많은(초과) 급여를 받은 직원의 이름, 급여, 부서코드를 조회

SELECT EMP_NAME, SALARY, DEPT_ID
FROM EMPLOYEE
WHERE DEPT_ID=90 OR DEPT_ID=20
AND SALARY > 3000000 ;

SELECT EMP_NAME, SALARY, DEPT_ID
FROM EMPLOYEE
WHERE DEPT_ID IN ('20','90')
AND SALARY > 3000000 ;

--TB_xxxx 실습

SELECT *
FROM TB_CLASS;