SELECT EMP_NAME,
       HIRE_DATE,
       TO_CHAR(HIRE_DATE , 'YYYY "년" MM "월" DD "일"'),
       SUBSTR(HIRE_DATE , 1, 2) || '년' ||
       SUBSTR(HIRE_DATE , 4, 2) || '월' ||
       SUBSTR(HIRE_DATE , 7, 2) || '일' AS 입사일
FROM EMPLOYEE;

-- SUBSTR(문자|날짜)
-- TO_DATE 는 문자열 정수값을 받는다. 앞에 들어오는 정확한 포맷에 맞는 형식을 지정해줘야 한다.
SELECT TO_DATE('20210119', 'YYYYMMDD') 
FROM DUAL;

-- TO_CHAR 날짜나 숫자를 받아서 문자를 만드는 것
-- 아래 코드는 오류가 발생
SELECT TO_CHAR('20210119', 'YYYY, MON')
FROM DUAL;
-- TO_DATE로 바꿔주고 TO_CHAR에 넣어줘야 오류 발생 X

SELECT TO_CHAR( TO_DATE('20210119', 'YYYYMMDD'), 'YYYY, MON')
FROM DUAL;

SELECT TO_DATE( '041030 143000', 'YYMMDD HH24MISS' ) FROM DUAL ;

SELECT TO_CHAR( TO_DATE( '041030 143000', 'YYMMDD HH24MISS' ), 'DD-MON-YY HH:MI:SS PM' ) FROM DUAL;

SELECT TO_DATE( '980630', 'YYMMDD' ) FROM DUAL;

SELECT TO_CHAR( TO_DATE( '980630', 'YYMMDD') , 'YYYY.MM.DD') FROM DUAL;