SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE DEPT_ID = '50'
OR DEPT_ID IS NULL
ORDER BY SALARY DESC;

SELECT EMP_NAME, HIRE_DATE, DEPT_ID
FROM EMPLOYEE
WHERE HIRE_DATE > TO_DATE('20030101', 'YYYYMMDD')
ORDER BY DEPT_ID DESC, HIRE_DATE, EMP_NAME;

--SELECT 절에서 AS를 사용한 별칭을 이용하여 ORDER BY 구문에서 실행할 수 있다.
SELECT EMP_NAME AS 이름,
       HIRE_DATE AS 입사일,
       DEPT_ID AS 부서코드
FROM EMPLOYEE
WHERE HIRE_DATE > TO_DATE('20030101', 'YYYYMMDD')
ORDER BY 부서코드 DESC, 입사일, 이름;

--SELECT 절에 기술된 순서로 표시가 가능하다.
SELECT EMP_NAME AS 이름,
       HIRE_DATE AS 입사일,
       DEPT_ID AS 부서코드
FROM EMPLOYEE
WHERE HIRE_DATE > TO_DATE('20030101', 'YYYYMMDD')
ORDER BY 3 DESC, 2, 1;