# Generated by Django 3.1.6 on 2021-02-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('prep', '준비중'), ('ord', '주문'), ('done', '완료')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobtitle',
            field=models.CharField(choices=[('J10', 'CEO'), ('J50', '아르바이트'), ('J40', '사원'), ('J20', '메니저'), ('J30', '메니저')], max_length=20),
        ),
    ]
