# Generated by Django 3.1.6 on 2021-02-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_username', models.CharField(max_length=50, verbose_name='신규 사용자명')),
                ('new_password', models.CharField(max_length=50, verbose_name='신규 비밀번호')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='registered_dttm',
        ),
    ]
