# Generated by Django 3.1.6 on 2021-02-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0002_auto_20210209_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordertime',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('done', '완료'), ('prep', '준비중'), ('ord', '주문')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='menuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_menu', to='mapleApp.menu'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='orderno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orderno', to='mapleApp.order'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobtitle',
            field=models.CharField(choices=[('J40', '인턴'), ('J30', '사원'), ('J20', '메니저'), ('J10', 'CEO'), ('J50', '아르바이트')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='info',
            table='m_info',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='m_menu',
        ),
        migrations.AlterModelTable(
            name='order',
            table='m_order',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='m_orderdetail',
        ),
        migrations.AlterModelTable(
            name='sampleproduct',
            table='m_sampleproduct',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='m_staff',
        ),
        migrations.AlterModelTable(
            name='user',
            table='m_user',
        ),
    ]
