# Generated by Django 3.1.5 on 2021-02-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0002_auto_20210212_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='odno',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('card', '카드'), ('cash', '현금')], max_length=20, verbose_name='결제구분'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('done', '완료'), ('ord', '주문'), ('prep', '준비중')], max_length=20, verbose_name='완료여부'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobtitle',
            field=models.CharField(choices=[('J40', '인턴'), ('J30', '사원'), ('J20', '메니저'), ('J10', 'CEO'), ('J50', '아르바이트')], max_length=20, verbose_name='직급'),
        ),
    ]
