# Generated by Django 2.1.15 on 2021-02-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'm_info',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('menuname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'm_menu',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('orderdate', models.CharField(default='', max_length=10)),
                ('ordertime', models.CharField(default='', max_length=10)),
                ('payment', models.CharField(choices=[('card', '카드'), ('cash', '현금')], max_length=20)),
                ('status', models.CharField(choices=[('done', '완료'), ('ord', '주문'), ('prep', '준비중')], max_length=20)),
            ],
            options={
                'db_table': 'm_order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('menuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_menu', to='mapleApp.Menu')),
                ('orderno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orderno', to='mapleApp.Order')),
            ],
            options={
                'db_table': 'm_orderdetail',
            },
        ),
        migrations.CreateModel(
            name='SampleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_name', models.CharField(max_length=100)),
                ('pd_price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'm_sampleproduct',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=20)),
                ('staffname', models.CharField(max_length=20)),
                ('jobtitle', models.CharField(choices=[('J20', '메니저'), ('J10', 'CEO'), ('J30', '사원'), ('J40', '인턴'), ('J50', '아르바이트')], max_length=20)),
                ('startdate', models.DateTimeField()),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'm_staff',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='사용자')),
                ('user_pwd', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('user_mail', models.CharField(max_length=100, verbose_name='이메일주소')),
            ],
            options={
                'db_table': 'm_user',
            },
        ),
        migrations.AlterUniqueTogether(
            name='info',
            unique_together={('type', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('orderno', 'menuid')},
        ),
    ]
