# Generated by Django 2.1.15 on 2021-02-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('prep', '준비중'), ('done', '완료'), ('ord', '주문')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobtitle',
            field=models.CharField(choices=[('J40', '인턴'), ('J30', '사원'), ('J50', '아르바이트'), ('J20', '메니저'), ('J10', 'CEO')], max_length=20),
        ),
    ]
