# Generated by Django 3.1.5 on 2021-02-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=50)),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_price', models.CharField(max_length=50)),
            ],
        ),
    ]
