# Generated by Django 3.1.5 on 2021-02-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleproduct',
            name='menu_id',
        ),
        migrations.AlterField(
            model_name='sampleproduct',
            name='menu_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sampleproduct',
            name='menu_price',
            field=models.FloatField(max_length=50),
        ),
    ]
