# Generated by Django 3.1.5 on 2021-02-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0002_auto_20210202_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleproduct',
            old_name='menu_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='sampleproduct',
            old_name='menu_price',
            new_name='product_price',
        ),
    ]
