# Generated by Django 3.1.5 on 2021-02-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0005_auto_20210203_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleproduct',
            old_name='pro_name',
            new_name='pd_name',
        ),
        migrations.RenameField(
            model_name='sampleproduct',
            old_name='pro_price',
            new_name='pd_price',
        ),
    ]
